# Add account credentials and API keys here.
# See http://railsapps.github.com/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable and overrides ENV variables in the Unix shell.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]
# Add application configuration variables here, as shown below.

# GOOGLE ANALYTICS
GOOGLE_ANALYTICS: UA-XXXXXXXX-X

# SEARCH ENGINE META AND SHARING
TITLE: Page Title
DESCRIPTION: Some descriptive text about this site
SHARE_COPY: Sitename - some tagline. Signup today to be first in line #Should be less than 110 characters and is used for both Twitter and LinkedIn.
TWITTER_HANDLE: kimmanis #Used for data-related in Twitter